name: easy_onvif_cli
version: 3.1.3
homepage: https://github.com/faithoflifedev/easy_onvif_workspace/tree/main/packages/easy_onvif_cli
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices.
repository: https://github.com/faithoflifedev/easy_onvif_workspace

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.7.0 <4.0.0"

executables:
  onvif:

dependencies:
  archive: ^4.0.5
  args: ^2.7.0
  ansicolor: ^2.0.3
  ansi_escapes: ^2.0.0
  cli_spin: ^1.0.1
  easy_onvif: ^3.1.3
  # easy_onvif:
  #   path: ../easy_onvif
  dio: ^5.7.0
  loggy: ^2.0.3
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uuid: ^4.5.1
  yaml: ^3.1.2

dev_dependencies:
  publish_tools: ^1.0.0+11
